"""preferred role on profile

Revision ID: a88fd527ec65
Revises: 03f5d5f97dca
Create Date: 2026-09-21 14:32:34.795792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88fd527ec65'
down_revision: Union[str, None] = '03f5d5f97dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('preferred_role', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'preferred_role')
    # ### end Alembic commands ###
